sudo: required
language: ruby
cache:
  directories:
  - vendor/bundle
  - node_modules
  - "$HOME/.nvm"
rvm:
- 2.6.3
addons:
  postgresql: '9.6'
  chrome: stable
env:
  global:
  - RAILS_ENV=test
  - CC_TEST_REPORTER_ID=63442e24fea11d49452afb81b26323c6e20b01a7a274d0c291bf4cc37fcdb91c
  - DATABASE_URL=postgres://postgres@localhost/
  - COVERAGE=true
branches:
  only:
  - master
before_install:
- date --rfc-3339=seconds
- nvm install
install:
- bundle install --path vendor/bundle
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
before_script:
- bundle exec rails db:create
script:
- bundle exec rails db:schema:load
- "./cc-test-reporter before-build"
- bundle exec rspec spec --color --tty
- "[ ! -f .approvals ] || bundle exec approvals verify --ask false"
- "./cc-test-reporter format-coverage -t simplecov -o coverage/codeclimate.simplecov.json"
- "./cc-test-reporter sum-coverage coverage/codeclimate.*.json"
- "./cc-test-reporter upload-coverage"
- bundle exec bundle-audit check --update --ignore CVE-2015-9284
notifications:
  slack:
    secure: XmVmY0mhPlASorefaPW9dg7yhxeDG9aPz8q+nGRS1kpZ6EJbRDMqm48kI2m5cygbidd6TNlrU11d0w8JsCVeELo/42H2FuFndE1S09D/FVmJP+ykDXePhx/FJOgTD5Ztd+lYa3qDZQNn36/vQx2byp1qH05dBDK7afi9fXbBP64J568ZkulwxIWWrJq7Qv8wUk4ZN7Yq98+f8mIqccAPmfMUnkw1z38N3jhortHu33hx8uMh5M5LSRG04g1WhIcPHIXEFepU43EX3veVxVZv/i8ZNweLesffpM+dvTYyzU1RivR3S++qtxERHgbSXacwT57LH8gK/K3gxW5YaN0ydqHKwwzoXKO7W1/SHMjMBu7ZELCq/+U6zXtyJrh6d5V/qBjqAxXAya7A78I7POVBipGTEBhvAoFCNtn9ApR+thGz6jvoOn4EbOHhJ6YRJG5NKP6ecLy9YxKoHgu9VF2+HZl6/sOxjBMNZ4XbzXoxS+EnI5nEgGlRPYY5cQrOpf0JIl2NSjQ6rPR02ov/H75fGagjw3wM5VGzWDf3KtZwzj0VuLi4edXjOtWmndX2tCsMazn2VbF8H+Zod+EAzvKSosJs+zM/zGpVrEYwKm7u2Nxy7gj2LZaRNNAk6+vhq61vMD8b9/oU2KGhOT7tqSrKXSs1hRj6v7jdjqZnzQKJORA=
