sudo: required
language: ruby
cache:
  directories:
    - vendor/bundle
    - node_modules
    - $HOME/.nvm
rvm:
  - 2.6.3
addons:
  postgresql: '9.6'
  chrome: 'stable'
env:
  global:
    - RAILS_ENV=test
    - CC_TEST_REPORTER_ID=63442e24fea11d49452afb81b26323c6e20b01a7a274d0c291bf4cc37fcdb91c
    - DATABASE_URL=postgres://postgres@localhost/
    - COVERAGE=true
branches:
  only:
    - master
before_install:
  - date --rfc-3339=seconds
  - nvm install
install:
  - bundle install --path vendor/bundle
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
    > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
before_script:
  - bundle exec rails db:create
script:
  - bundle exec rails db:schema:load
  - './cc-test-reporter before-build'
  - 'bundle exec rspec spec --color --tty'
  - '[ ! -f .approvals ] || bundle exec approvals verify --ask false'
  - './cc-test-reporter format-coverage -t simplecov -o coverage/codeclimate.simplecov.json'
  - './cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.lcov.json'
  - './cc-test-reporter sum-coverage coverage/codeclimate.*.json'
  - './cc-test-reporter upload-coverage'
  - 'bundle exec bundle-audit check --update --ignore CVE-2015-9284'